"""Scenario-driven LCZ time-series classification.

This module implements three classification workflows that produce annual LCZ
maps from Google Earth Engine assets.  Each scenario differs in how training
samples are obtained and how the final per-year results are assembled:

Scenario 1 – Yearly sample assets
    A dedicated training-sample asset exists for every target year.  Features
    are extracted from Landsat composites (≤ 2016) or the Google Satellite
    Embedding collection (> 2016), and a Random Forest classifier is trained
    independently for each year.  A focal-mode spatial filter is applied after
    classification.

Scenario 2 – Single-year sample with YOD-guided fusion
    A single training-sample asset (typically the most recent reliable year) is
    reused across all years.  For years ≤ 2016 a *hybrid* strategy is used:
    stable pixels (YOD = 0) are sampled from the fixed asset while *ghost*
    samples are drawn from the FROM-GLC Plus land-cover product in areas of
    detected change (YOD ≠ 0).  The final map is assembled by using the GLC
    guide as a base and replacing built-up pixels (lc_label = 8) with the RF
    result.  For years > 2016 only the stable samples are used and the RF
    result is taken directly.

Scenario 3 – No external samples; confidence-mask based
    No pre-labelled training assets are required.  Instead, a 2020 LCZ product
    is used as pseudo-labels.  A *confidence mask* is generated by running
    three independent RF classifiers on the 2020 embedding features and
    retaining only pixels where all three predictions agree with each other and
    with the pseudo-label.  The confidence mask is exported as a GEE asset and
    then used as the stable-area mask for the final per-year classification.
    Landsat years use a GLC-guided label fused with the 2020 product; built-up
    pixels (lc_label = 8) are replaced by the RF result.
"""

from __future__ import annotations

from typing import Dict, Iterable, List, Optional

import ee

from utils import config as Config
from utils.geemodules import ChangeDetector, LCZClassifier, TemporalAggregator


# ---------------------------------------------------------------------------
# Internal helpers shared across scenarios
# ---------------------------------------------------------------------------

def _get_landsat_features(year: int, city_id: int, region: ee.Geometry) -> ee.Image:
    """Return a Landsat feature image with spectral indices and NIR texture.

    Handles both Landsat 5/7 (SR_B1 … SR_B7) and Landsat 8/9 (SR_B2 … SR_B7)
    band layouts.  Falls back to legacy band names when neither layout matches.
    """
    from utils.processors import AssetManager

    asset_path = AssetManager.get_existing_asset_path(year, city_id)
    if not asset_path:
        raise ValueError(f"No Landsat asset found for city {city_id}, year {year}")

    img = ee.Image(asset_path).clip(region)
    bnames = img.bandNames()
    dst = ["blue", "green", "red", "nir", "swir1", "swir2"]

    base = ee.Image(ee.Algorithms.If(
        bnames.contains("SR_B6"),
        img.select(["SR_B2", "SR_B3", "SR_B4", "SR_B5", "SR_B6", "SR_B7"], dst),
        ee.Algorithms.If(
            bnames.contains("SR_B1"),
            img.select(["SR_B1", "SR_B2", "SR_B3", "SR_B4", "SR_B5", "SR_B7"], dst),
            img.select(["B1", "B2", "B3", "B4", "B5", "B7"], dst),
        ),
    ))

    ndvi = base.normalizedDifference(["nir", "red"]).rename("NDVI")
    ndbi = base.normalizedDifference(["swir1", "nir"]).rename("NDBI")
    mndwi = base.normalizedDifference(["green", "swir1"]).rename("MNDWI")
    nir_std = base.select("nir").reduceNeighborhood(
        reducer=ee.Reducer.stdDev(),
        kernel=ee.Kernel.square(3),
    ).rename("NIR_STD")

    return base.addBands([ndvi, ndbi, mndwi, nir_std])


def _get_embedding_features(year: int, region: ee.Geometry) -> Optional[ee.Image]:
    """Return a mosaicked Google Satellite Embedding image for *year*.

    Returns ``None`` when the collection is empty for the requested year.
    """
    collection_id = getattr(Config, "ALPHA_EARTH_COLLECTION", None)
    if not collection_id:
        return None

    start = ee.Date.fromYMD(year, 1, 1)
    end = ee.Date.fromYMD(year, 12, 31)

    col = (
        ee.ImageCollection(collection_id)
        .filterDate(start, end)
        .filterBounds(region)
    )
    # Use EE-side conditional to avoid pulling collection size to the client.
    # col.size().getInfo() on a large region can exceed the user memory limit.
    img = ee.Image(
        ee.Algorithms.If(
            col.size().gt(0),
            col.mosaic().clip(region),
            ee.Image(0),   # sentinel – detected below
        )
    )
    # Detect the sentinel without any .getInfo() call:
    # Check whether the first band is named 'constant' using a server-side
    # string comparison.  This avoids pulling any data to the client.
    first_band = img.bandNames().get(0)
    is_sentinel = ee.String(first_band).equals("constant")

    # Build the renamed image only when the collection was non-empty.
    # We use ee.Algorithms.If to keep everything server-side.
    bands = img.bandNames()
    renamed = img.select(
        bands,
        bands.map(lambda b: ee.String("EMB_").cat(ee.String(b))),
    ).clip(region)

    # Pull a single boolean to the client – negligible memory cost.
    try:
        if is_sentinel.getInfo():
            return None
    except Exception:
        return None

    return renamed


def _get_features_by_year(
    year: int,
    city_id: int,
    region: ee.Geometry,
) -> Optional[ee.Image]:
    """Select the appropriate feature image based on *year*.

    Uses Landsat for years ≤ 2016 and the Satellite Embedding for later years,
    falling back to Landsat when the embedding collection is unavailable.
    """
    if year <= 2016:
        return _get_landsat_features(year, city_id, region)

    emb = _get_embedding_features(year, region)
    if emb is not None:
        return emb

    # Graceful fallback: use Landsat even for post-2016 years
    return _get_landsat_features(year, city_id, region)


def _apply_smoothing(img: ee.Image, class_field: str, region: ee.Geometry) -> ee.Image:
    """Apply a circular focal-mode filter and clip to *region*."""
    return (
        img.focal_mode(radius=1.5, kernelType="circle", units="pixels", iterations=1)
        .toInt16()
        .rename(class_field)
        .clip(region)
    )


def _stratified_sample_n_per_class(
    sampling_img: ee.Image,
    region: ee.Geometry,
    n_per_class: int,
    seed: int,
    class_field: str,
    tile_scale: int = 4,
    geometries: bool = False,
) -> ee.FeatureCollection:
    """Stratified sample with a fixed quota per LCZ class (1–17)."""
    class_values = ee.List.sequence(1, 17)
    class_points = ee.List.repeat(n_per_class, 17)
    return sampling_img.stratifiedSample(
        numPoints=0,
        classBand=class_field,
        region=region,
        scale=Config.SCALE,
        seed=seed,
        classValues=class_values,
        classPoints=class_points,
        geometries=geometries,
        dropNulls=True,
        tileScale=tile_scale,
    )


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------


class LCZTimeSeriesScenarios:
    """Run the three LCZ time-series classification scenarios.

    Parameters
    ----------
    years:
        Target years.  Defaults to ``Config.YEARS``.
    base_year:
        Reference year (used as the latest anchor for backfilling).  Defaults
        to the maximum of *years*.
    samples_per_class:
        Number of training samples per LCZ class (Scenarios 1 & 2).
    ghost_samples_per_class:
        Number of ghost samples per class drawn from FROM-GLC Plus (Scenario 2
        hybrid strategy).
    samples_asset_template:
        Path template for per-year sample assets used by Scenario 1.  Must
        contain a ``{year}`` placeholder, e.g.
        ``"users/xxx/Samples/training{year}"``.  Falls back to
        ``Config.CLASS_SCENARIO1_SAMPLE_TEMPLATE`` when ``None``.
    samples_asset:
        Fixed sample asset path used by Scenario 2.  Falls back to
        ``Config.CLASS_SCENARIO2_SAMPLE_ASSET`` when ``None``.
    yod_asset:
        Year-of-disturbance asset path used by Scenarios 2 and 3.  Falls back
        to ``Config.CLASS_SCENARIO2_YOD_ASSET`` and then to
        ``{LCZ_YOD}YOD_{city_id}_open`` when ``None``.
    map_2020_asset_id:
        2020 LCZ product asset used as pseudo-labels in Scenario 3.  Falls
        back to ``Config.CLASS_SCENARIO3_MAP_2020_ASSET``.
    confi_mask_asset_out:
        Output asset path for the Scenario 3 confidence mask.  Falls back to
        ``Config.CLASS_SCENARIO3_CONFI_MASK_OUT``.
    samples_class_property:
        Name of the class property in training sample feature collections.
        Defaults to ``"LCZ"``.
    feature_source:
        ``"auto"`` (default) selects Landsat for ≤ 2016 and Embedding for
        later years; ``"landsat"`` always uses Landsat; ``"embedding"`` always
        uses the Embedding collection.
    include_alpha_embedding:
        When ``True``, appends Embedding bands to Landsat features (passed
        through to the underlying ``LCZClassifier``).
    seed:
        Global random seed.
    n_per_class:
        Samples per class for the final classification in Scenario 3.  Falls
        back to ``Config.CLASS_SCENARIO3_SAMPLES_PER_CLASS``.
    cf_n_per_class:
        Samples per class for each confidence-mask RF round (Scenario 3).
    cf_rounds:
        Number of independent RF rounds used to build the confidence mask.
    cf_rf_trees:
        Number of trees per RF round in the confidence-mask step.
    cf_seeds:
        Fixed seeds for the confidence-mask RF rounds.
    tile_scale:
        ``tileScale`` passed to EE sampling calls in Scenario 3.
    """

    def __init__(
        self,
        years: Optional[Iterable[int]] = None,
        base_year: Optional[int] = None,
        samples_per_class: int = 200,
        ghost_samples_per_class: int = 150,
        samples_asset_template: Optional[str] = None,
        samples_asset: Optional[str] = None,
        yod_asset: Optional[str] = None,
        map_2020_asset_id: Optional[str] = None,
        confi_mask_asset_out: Optional[str] = None,
        samples_class_property: str = "LCZ",
        feature_source: str = "auto",
        include_alpha_embedding: bool = False,
        seed: int = 42,
        n_per_class: Optional[int] = None,
        cf_n_per_class: Optional[int] = None,
        cf_rounds: Optional[int] = None,
        cf_rf_trees: Optional[int] = None,
        cf_seeds: Optional[List[int]] = None,
        tile_scale: Optional[int] = None,
    ) -> None:
        self.years = list(years) if years is not None else Config.YEARS
        self.base_year = base_year if base_year is not None else max(self.years)
        self.samples_per_class = samples_per_class
        self.ghost_samples_per_class = ghost_samples_per_class
        self.class_field = samples_class_property
        self.feature_source = feature_source
        self.seed = seed

        # Scenario 1
        self.samples_asset_template = (
            samples_asset_template
            or getattr(Config, "CLASS_SCENARIO1_SAMPLE_TEMPLATE", None)
        )

        # Scenario 2
        self.samples_asset = (
            samples_asset
            or getattr(Config, "CLASS_SCENARIO2_SAMPLE_ASSET", None)
        )
        self._yod_asset_override = (
            yod_asset
            or getattr(Config, "CLASS_SCENARIO2_YOD_ASSET", None)
        )
        self.lc_template = getattr(Config, "CLASS_SCENARIO2_LC_TEMPLATE",
                                   "projects/globallcz/assets/fromglc_plus/plus_{year}")
        self.glc_map = getattr(Config, "GLC_TO_LCZ_MAP", {})
        self.ghost_points = getattr(Config, "CLASS_SCENARIO2_GHOST_POINTS", 500)

        # Scenario 3
        self.map_2020_asset_id = (
            map_2020_asset_id
            or getattr(Config, "CLASS_SCENARIO3_MAP_2020_ASSET", None)
        )
        self.confi_mask_asset_out = (
            confi_mask_asset_out
            or getattr(Config, "CLASS_SCENARIO3_CONFI_MASK_OUT", None)
        )
        # Pseudo-label source: "image" (default) or "global_lcz"
        self.pseudo_label_source = getattr(
            Config, "CLASS_SCENARIO3_PSEUDO_LABEL_SOURCE", "image"
        )
        self.global_lcz_collection = getattr(
            Config, "CLASS_SCENARIO3_GLOBAL_LCZ_COLLECTION",
            "RUB/RUBCLIM/LCZ/global_lcz_map/latest",
        )
        self.global_lcz_band = getattr(
            Config, "CLASS_SCENARIO3_GLOBAL_LCZ_BAND", "LCZ_Filter"
        )
        self.lc_template_s3 = getattr(Config, "CLASS_SCENARIO3_LC_TEMPLATE",
                                      "projects/globallcz/assets/fromglc_plus/plus_{year}")
        self.n_per_class = (
            n_per_class
            or getattr(Config, "CLASS_SCENARIO3_SAMPLES_PER_CLASS", 300)
        )
        self.cf_n_per_class = (
            cf_n_per_class
            or getattr(Config, "CLASS_SCENARIO3_CF_N_PER_CLASS", 100)
        )
        self.cf_rounds = (
            cf_rounds
            or getattr(Config, "CLASS_SCENARIO3_CF_ROUNDS", 3)
        )
        self.cf_rf_trees = (
            cf_rf_trees
            or getattr(Config, "CLASS_SCENARIO3_CF_RF_TREES", 100)
        )
        self.cf_seeds = (
            cf_seeds
            or getattr(Config, "CLASS_SCENARIO3_CF_SEEDS", [1001, 1002, 1003])
        )
        self.tile_scale = (
            tile_scale
            or getattr(Config, "CLASS_SCENARIO3_TILE_SCALE", 8)
        )

        self.classifier = LCZClassifier(
            num_trees=getattr(Config, "CLASSIFIER_TREES", 150),
            samples_per_class=samples_per_class,
            seed=seed,
            use_alpha_embedding=include_alpha_embedding,
        )
        self.detector = ChangeDetector()

    # ------------------------------------------------------------------
    # Region helpers
    # ------------------------------------------------------------------

    def _get_region_feature(self, city_id: int) -> ee.Feature:
        return Config.get_region_fc().filter(ee.Filter.eq("id", int(city_id))).first()

    def _get_region_geometry(self, city_id: int) -> ee.Geometry:
        return self._get_region_feature(city_id).geometry()

    def _get_yod_img(self, city_id: int, region: ee.Geometry) -> ee.Image:
        if self._yod_asset_override:
            return ee.Image(self._yod_asset_override).unmask(0).clip(region)
        fallback = f"{Config.GEE_ASSETS['LCZ_YOD']}YOD_{city_id}_open"
        return ee.Image(fallback).unmask(0).clip(region)

    def _get_landcover_img(self, year: int, region: ee.Geometry,
                           template: Optional[str] = None) -> ee.Image:
        tmpl = template or self.lc_template
        return (
            ee.Image(tmpl.format(year=year))
            .select(0)
            .rename("lc_label")
            .unmask(0)
            .clip(region)
        )

    def _get_features(self, year: int, city_id: int,
                      region: ee.Geometry) -> Optional[ee.Image]:
        src = self.feature_source
        if src == "landsat":
            return _get_landsat_features(year, city_id, region)
        if src == "embedding":
            return _get_embedding_features(year, region)
        return _get_features_by_year(year, city_id, region)

    # ------------------------------------------------------------------
    # Scenario 1 – yearly sample assets
    # ------------------------------------------------------------------

    def scenario_one(self, city_id: int) -> ee.ImageCollection:
        """Classify each year using its own dedicated sample asset.

        For every year in ``self.years`` the method:

        1. Loads the per-year sample asset at the path given by
           ``samples_asset_template.format(year=year)``.
        2. Extracts feature values at the sample locations from the
           corresponding Landsat / Embedding image.
        3. Trains a Random Forest and classifies the full image.
        4. Applies a focal-mode spatial filter.

        Returns
        -------
        ee.ImageCollection
            One image per year, each with a single band named ``LCZ_{year}``
            and a ``year`` property.
        """
        if not self.samples_asset_template:
            raise ValueError(
                "samples_asset_template (or Config.CLASS_SCENARIO1_SAMPLE_TEMPLATE) "
                "must be set to run Scenario 1."
            )

        region = self._get_region_geometry(city_id)
        images = []

        for year in self.years:
            feat_img = self._get_features(year, city_id, region)
            if feat_img is None:
                print(f"[Scenario 1] Skip {year}: feature image unavailable")
                continue

            sample_path = self.samples_asset_template.format(year=year)
            pts = ee.FeatureCollection(sample_path).filterBounds(region)

            training = feat_img.sampleRegions(
                collection=pts,
                properties=[self.class_field],
                scale=Config.SCALE,
                geometries=False,
                tileScale=getattr(Config, "CLASS_SCENARIO3_TILE_SCALE", 16),
            )

            # Do NOT call training.size().getInfo().
            # sampleRegions on a large FeatureCollection triggers full pixel-
            # level computation on the client, exceeding the user memory limit.
            # Pass training directly to RF.train(); GEE evaluates it lazily.
            bands = feat_img.bandNames()
            rf = ee.Classifier.smileRandomForest(
                getattr(Config, "CLASSIFIER_TREES", 150)
            ).train(training, self.class_field, bands)

            classified = feat_img.classify(rf)
            smoothed = _apply_smoothing(classified, f"LCZ_{year}", region)
            images.append(smoothed.set("year", year))

        if not images:
            raise ValueError("Scenario 1 produced no classification results.")

        return ee.ImageCollection.fromImages(images)

    # ------------------------------------------------------------------
    # Scenario 2 – single-year sample + YOD-guided fusion
    # ------------------------------------------------------------------

    def scenario_two(self, city_id: int) -> ee.ImageCollection:
        """Classify all years reusing a single fixed-year sample asset.

        The method applies two sample strategies depending on the year:

        - **HYBRID** (year ≤ 2016): stable pixels from the fixed sample asset
          (masked to YOD = 0) are combined with ghost samples drawn from the
          FROM-GLC Plus land-cover product in areas of detected change
          (YOD ≠ 0).  The final map uses the GLC guide as a base layer and
          replaces built-up pixels (``lc_label = 8``) with the RF result.
        - **STABLE** (year > 2016): only the stable pixels from the fixed
          sample asset are used, and the RF result is taken directly.

        Returns
        -------
        ee.ImageCollection
            One image per year, each with a single band named ``LCZ_{year}``
            and a ``year`` property.
        """
        if not self.samples_asset:
            raise ValueError(
                "samples_asset (or Config.CLASS_SCENARIO2_SAMPLE_ASSET) "
                "must be set to run Scenario 2."
            )

        region = self._get_region_geometry(city_id)
        yod_img = self._get_yod_img(city_id, region)
        images = []

        for year in self.years:
            feat_img = self._get_features(year, city_id, region)
            lc_img = self._get_landcover_img(year, region)

            if feat_img is None:
                print(f"[Scenario 2] Skip {year}: feature image unavailable")
                continue

            raw_pts = ee.FeatureCollection(self.samples_asset).filterBounds(region)
            stable_mask = yod_img.eq(0)

            stable_samples = feat_img.updateMask(stable_mask).sampleRegions(
                collection=raw_pts,
                properties=[self.class_field],
                scale=Config.SCALE,
                geometries=False,
            )

            if year <= 2016:
                # HYBRID: add ghost samples from GLC in changed areas
                lcz_guide = lc_img.remap(
                    list(self.glc_map.keys()),
                    list(self.glc_map.values()),
                    0,
                ).rename(self.class_field).toByte()

                unstable_mask = yod_img.neq(0)
                ghost_mask = unstable_mask.And(lcz_guide.neq(0))
                ghost_input = feat_img.addBands(lcz_guide)

                ghost_samples = ghost_input.updateMask(ghost_mask).stratifiedSample(
                    numPoints=self.ghost_points,
                    classBand=self.class_field,
                    region=region,
                    scale=Config.SCALE,
                    geometries=False,
                    dropNulls=True,
                )
                training = stable_samples.merge(ghost_samples)
            else:
                lcz_guide = None
                training = stable_samples

            # Do NOT call training.size().getInfo() – same reason as Scenario 1.
            bands = feat_img.bandNames()
            rf = ee.Classifier.smileRandomForest(
                getattr(Config, "CLASSIFIER_TREES", 150)
            ).train(training, self.class_field, bands)
            rf_result = feat_img.classify(rf).toInt16()

            if year <= 2016 and lcz_guide is not None:
                # Use GLC guide as base; replace lc_label==8 pixels with RF
                replace_mask = lc_img.eq(8)
                combined = lcz_guide.toInt16().where(replace_mask, rf_result)
            else:
                combined = rf_result

            smoothed = _apply_smoothing(combined, f"LCZ_{year}", region)
            images.append(smoothed.set("year", year))

        if not images:
            raise ValueError("Scenario 2 produced no classification results.")

        return ee.ImageCollection.fromImages(images)

    # ------------------------------------------------------------------
    # Scenario 3 – confidence-mask based, no external samples
    # ------------------------------------------------------------------

    def _load_pseudo_label(self, region: ee.Geometry) -> ee.Image:
        """Return the pseudo-label image for Scenario 3.

        Two sources are supported, selected by ``self.pseudo_label_source``:

        ``"image"``
            Load a single custom GEE Image asset specified by
            ``self.map_2020_asset_id``.  The asset must contain a band named
            ``"remapped"`` that holds integer LCZ class values (1–17).

        ``"global_lcz"``
            Use the GEE official global LCZ ImageCollection
            ``ee.ImageCollection("RUB/RUBCLIM/LCZ/global_lcz_map/latest")``.
            The collection is filtered to the city boundary, mosaicked, and the
            band selected by ``self.global_lcz_band`` (``"LCZ_Filter"`` or
            ``"LCZ_Majority"``) is used.  No additional asset path is required.

        Returns
        -------
        ee.Image
            Single-band image named ``self.class_field`` with integer LCZ
            values 1–17 and pixels outside the valid range masked out.
        """
        if self.pseudo_label_source == "global_lcz":
            col = (
                ee.ImageCollection(self.global_lcz_collection)
                .filterBounds(region)
            )
            # Mosaic all tiles that intersect the city boundary
            raw = col.select(self.global_lcz_band).mosaic().clip(region)
            # The global LCZ collection uses values 1–17 directly
            lcz = (
                raw
                .rename(self.class_field)
                .toInt16()
                .updateMask(raw.gte(1).And(raw.lte(17)))
            )
            return lcz

        # Default: "image" – load a single custom asset
        if not self.map_2020_asset_id:
            raise ValueError(
                "map_2020_asset_id (or Config.CLASS_SCENARIO3_MAP_2020_ASSET) "
                "must be set when SCENARIO3_PSEUDO_LABEL_SOURCE = 'image'."
            )
        raw = (
            ee.Image(self.map_2020_asset_id)
            .select("remapped")
            .toInt16()
            .clip(region)
        )
        lcz = raw.rename(self.class_field).updateMask(raw.gt(0))
        return lcz

    def _train_and_classify_once(
        self,
        feat: ee.Image,
        label_img: ee.Image,
        region: ee.Geometry,
        n_per_class: int,
        seed: int,
        out_band: str,
        rf_trees: int = 100,
    ) -> ee.Image:
        """Train one RF on stratified pseudo-label samples and classify *feat*."""
        train_pts = _stratified_sample_n_per_class(
            label_img, region, n_per_class, seed,
            class_field=self.class_field,
            tile_scale=self.tile_scale,
            geometries=True,
        )
        train_fc = feat.sampleRegions(
            collection=train_pts,
            properties=[self.class_field],
            scale=Config.SCALE,
            geometries=False,
            tileScale=self.tile_scale,
        )
        rf = ee.Classifier.smileRandomForest(rf_trees).train(
            features=train_fc,
            classProperty=self.class_field,
            inputProperties=feat.bandNames(),
        )
        return feat.classify(rf).toInt16().rename(out_band)

    def build_confi_mask(self, city_id: int) -> Optional[ee.Image]:
        """Generate a confidence mask for *city_id* using the 2020 embedding.

        Three independent RF classifiers are trained on the 2020 pseudo-labels.
        A pixel is marked as *confident* (value = 1) when all three predictions
        agree with each other **and** all three equal the pseudo-label.

        The result is a byte image clipped to the city boundary.  Returns
        ``None`` when the embedding collection is empty for 2020.
        """
        # Validate that a pseudo-label source is available
        if self.pseudo_label_source != "global_lcz" and not self.map_2020_asset_id:
            raise ValueError(
                "map_2020_asset_id (or Config.CLASS_SCENARIO3_MAP_2020_ASSET) "
                "must be set when SCENARIO3_PSEUDO_LABEL_SOURCE = 'image'."
            )

        region = self._get_region_geometry(city_id)
        feat = _get_embedding_features(2020, region)
        if feat is None:
            print("[Scenario 3] build_confi_mask: 2020 embedding unavailable")
            return None

        lcz2020 = self._load_pseudo_label(region)
        label_img = lcz2020  # already masked and renamed by _load_pseudo_label

        pred_imgs = []
        for i in range(self.cf_rounds):
            seed = self.cf_seeds[i] if i < len(self.cf_seeds) else 1000 + i
            pred = self._train_and_classify_once(
                feat=feat,
                label_img=label_img,
                region=region,
                n_per_class=self.cf_n_per_class,
                seed=seed,
                out_band=f"pred_{i + 1}",
                rf_trees=self.cf_rf_trees,
            )
            pred_imgs.append(pred)

        pred1, pred2, pred3 = pred_imgs[0], pred_imgs[1], pred_imgs[2]

        # All three predictions agree with each other
        consistent_pred = pred1.eq(pred2).And(pred1.eq(pred3))

        # All three predictions equal the pseudo-label
        consistent_ref = (
            pred1.eq(lcz2020)
            .And(pred2.eq(lcz2020))
            .And(pred3.eq(lcz2020))
        )
        # (lcz2020 is already the correctly named/masked image from _load_pseudo_label)

        confi = (
            consistent_pred.And(consistent_ref)
            .rename("confi_mask")
            .toByte()
            .clip(region)
        )
        return confi

    def export_confi_mask(self, city_id: int) -> None:
        """Export the confidence mask to ``self.confi_mask_asset_out``.

        This must be called (and the EE task must complete) before running
        ``scenario_three`` with ``use_confi=True``.
        """
        if not self.confi_mask_asset_out:
            raise ValueError(
                "confi_mask_asset_out (or Config.CLASS_SCENARIO3_CONFI_MASK_OUT) "
                "must be set before exporting the confidence mask."
            )

        region = self._get_region_geometry(city_id)
        confi = self.build_confi_mask(city_id)
        if confi is None:
            print("[Scenario 3] export_confi_mask: skipped (no embedding data)")
            return

        task = ee.batch.Export.image.toAsset(
            image=confi,
            description=f"ConfiMask_{city_id}_2020",
            assetId=self.confi_mask_asset_out,
            region=region,
            scale=Config.SCALE,
            maxPixels=1e13,
        )
        task.start()
        print(f"[Scenario 3] Confidence mask export submitted: {self.confi_mask_asset_out}")

    def _classify_embedding_year_s3(
        self,
        year: int,
        region: ee.Geometry,
        use_confi: bool = True,
    ) -> Optional[ee.Image]:
        """Classify an embedding year for Scenario 3."""
        feat = _get_embedding_features(year, region)
        if feat is None:
            return None

        lcz2020 = self._load_pseudo_label(region)

        if use_confi and self.confi_mask_asset_out:
            confi = ee.Image(self.confi_mask_asset_out).clip(region).selfMask()
            sampling_img = feat.addBands(lcz2020).updateMask(confi)
        else:
            sampling_img = feat.addBands(lcz2020).updateMask(lcz2020.gt(0))

        samples = _stratified_sample_n_per_class(
            sampling_img, region,
            n_per_class=self.n_per_class,
            seed=self.seed + year,
            class_field=self.class_field,
            tile_scale=self.tile_scale,
            geometries=False,
        )

        # Do NOT call samples.size().getInfo() here.
        # stratifiedSample on a large region returns a FeatureCollection whose
        # size() evaluation triggers the full pixel-level computation
        # (mosaic + updateMask + stratifiedSample), exceeding the user memory
        # limit before any task is submitted.  Instead, pass samples directly
        # to RF.train(); GEE will evaluate it lazily inside the Export task.
        bands = feat.bandNames()
        rf = ee.Classifier.smileRandomForest(200).train(
            samples, self.class_field, bands
        )
        pred = feat.classify(rf).toInt16()
        return _apply_smoothing(pred, self.class_field, region)

    def _classify_landsat_year_s3(
        self,
        year: int,
        city_id: int,
        region: ee.Geometry,
    ) -> Optional[ee.Image]:
        """Classify a Landsat year for Scenario 3.

        The label image is built by fusing the FROM-GLC Plus land-cover guide
        with the 2020 LCZ product.  Built-up pixels (``lc_label = 8``) are
        replaced by the RF result after classification.
        """
        feat = _get_landsat_features(year, city_id, region)
        lc = self._get_landcover_img(year, region, template=self.lc_template_s3)

        # Build GLC-guided label
        lcz_guide = lc.remap(
            list(self.glc_map.keys()),
            list(self.glc_map.values()),
            0,
        ).rename(self.class_field).toInt16()

        lcz2020 = self._load_pseudo_label(region)

        # Replace guide with 2020 product everywhere, then mask to valid classes
        label = lcz_guide.where(ee.Image(1), lcz2020)
        label = label.updateMask(
            label.gte(1).And(label.lte(17))
        ).rename(self.class_field)

        sampling_img = feat.addBands(label)
        samples = _stratified_sample_n_per_class(
            sampling_img, region,
            n_per_class=self.n_per_class,
            seed=self.seed + year,
            class_field=self.class_field,
            tile_scale=self.tile_scale,
            geometries=False,
        )

        # Do NOT call samples.size().getInfo() here – same reason as in
        # _classify_embedding_year_s3: the size() call forces GEE to evaluate
        # the full stratifiedSample computation on the client, which exceeds
        # the user memory limit for large cities.  Pass samples directly to
        # RF.train() and let GEE evaluate lazily inside the Export task.
        bands = feat.bandNames()
        rf = ee.Classifier.smileRandomForest(200).train(
            samples, self.class_field, bands
        )
        rf_result = feat.classify(rf).toInt16()

        # Fuse: use GLC guide as base, replace lc_label==8 with RF result
        fused = lcz_guide.where(lc.eq(8), rf_result)
        return _apply_smoothing(fused, self.class_field, region)

    def scenario_three(
        self,
        city_id: int,
        use_confi: bool = True,
        export_confi_mask: bool = False,
    ) -> ee.ImageCollection:
        """Classify all years without external sample assets.

        The workflow proceeds in three stages:

        1. **Confidence mask** (optional export): if ``export_confi_mask`` is
           ``True`` the mask is exported to ``self.confi_mask_asset_out`` before
           classification.  The EE task must finish before the next run.
        2. **Embedding years** (``YEARS_EMB``): classified using the confidence
           mask as the stable-area mask (when ``use_confi=True``).
        3. **Landsat years** (remaining years): classified using a GLC-guided
           label fused with the 2020 LCZ product.

        Parameters
        ----------
        city_id:
            City identifier.
        use_confi:
            When ``True`` (default), the pre-exported confidence mask is used
            to restrict sampling in embedding years.  Set to ``False`` to use
            the full 2020 pseudo-label mask instead.
        export_confi_mask:
            When ``True``, export the confidence mask before running
            classification.  Requires ``confi_mask_asset_out`` to be set.

        Returns
        -------
        ee.ImageCollection
            One image per year, each with a single band named ``LCZ_{year}``
            and a ``year`` property.
        """
        if self.pseudo_label_source != "global_lcz" and not self.map_2020_asset_id:
            raise ValueError(
                "map_2020_asset_id (or Config.CLASS_SCENARIO3_MAP_2020_ASSET) "
                "must be set when SCENARIO3_PSEUDO_LABEL_SOURCE = 'image'."
            )

        if export_confi_mask:
            self.export_confi_mask(city_id)

        region = self._get_region_geometry(city_id)
        images = []

        for year in self.years:
            feat_img = self._get_features(year, city_id, region)
            if feat_img is None:
                print(f"[Scenario 3] Skip {year}: feature image unavailable")
                continue

            if year > 2016:
                # Embedding branch
                img = self._classify_embedding_year_s3(year, region, use_confi=use_confi)
            else:
                # Landsat branch
                img = self._classify_landsat_year_s3(year, city_id, region)

            if img is None:
                continue

            images.append(
                img.rename(f"LCZ_{year}")
                .set("year", year)
                .set("system:time_start", ee.Date.fromYMD(int(year), 1, 1).millis())
            )

        if not images:
            raise ValueError("Scenario 3 produced no classification results.")

        return ee.ImageCollection.fromImages(images)


__all__ = ["LCZTimeSeriesScenarios"]
